export const newsTicker = [
  {
    id: 1,
    currenyPair: "USD/NGN",
    buyRate: "910.90",
    sellRate: "910.89",
    trend: "up",
  },
  {
    id: 2,
    currenyPair: "USD/NGN",
    buyRate: "910.90",
    sellRate: "910.89",
    trend: "down",
  },
  {
    id: 3,
    currenyPair: "USD/NGN",
    buyRate: "910.90",
    sellRate: "910.89",
    trend: "up",
  },
  {
    id: 4,
    currenyPair: "USD/NGN",
    buyRate: "910.90",
    sellRate: "910.89",
    trend: "down",
  },
  {
    id: 5,
    currenyPair: "USD/NGN",
    buyRate: "910.90",
    sellRate: "910.89",
    trend: "up",
  },
  {
    id: 6,
    currenyPair: "USD/NGN",
    buyRate: "910.90",
    sellRate: "910.89",
    trend: "down",
  },
  {
    id: 7,
    currenyPair: "USD/NGN",
    buyRate: "910.90",
    sellRate: "910.89",
    trend: "up",
  },
  {
    id: 8,
    currenyPair: "USD/NGN",
    buyRate: "910.90",
    sellRate: "910.89",
    trend: "down",
  },
  {
    id: 9,
    currenyPair: "USD/NGN",
    buyRate: "910.90",
    sellRate: "910.89",
    trend: "up",
  },
  {
    id: 10,
    currenyPair: "USD/NGN",
    buyRate: "910.90",
    sellRate: "910.89",
    trend: "down",
  },
];
